# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: EshopCICD
trigger:
 - master

stages:
  - stage: Build
    jobs:
    - job: Build
      pool: Default
      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '8.0.302'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.sln'
            feedsToUse: 'select'
          displayName: Restore
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.sln'
          displayName: Build
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/UnitTests.csproj'
          displayName: Unit_Test
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            projects: '**/*.sln'
            arguments: '--configuration Release --output  $(Build.ArtifactStagingDirectory)'
          displayName: Publish
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'RetailApp'
          displayName: Publish_Artifact